import pygame
import sys
import random
import ctypes #the code to make the window appear transparent and always on top is generated by ai.

pygame.init()

screen = pygame.display.set_mode((250,250), pygame.NOFRAME)

hwnd = pygame.display.get_wm_info()['window'] #this line is ai generated. I don't know how to impliment c types

GWL_EXSTYLE = -20 #ai
WS_EX_LAYERED = 0x80000 #ai
LWA_COLORKEY = 0x1  #ai

user32 = ctypes.windll.user32 #ai
current_style = user32.GetWindowLongW(hwnd, GWL_EXSTYLE) #ai
user32.SetWindowLongW(hwnd, GWL_EXSTYLE, current_style | WS_EX_LAYERED) #ai
user32.SetLayeredWindowAttributes(hwnd, 0xFF00FF, 0, LWA_COLORKEY) #ai

HWND_TOPMOST = -1 #ai
SWP_NOMOVE = 0x2 #ai
SWP_NOSIZE = 0x1 #ai

user32.SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE) #ai

x = 75
y = 75

frame1 = pygame.image.load("blue1.png")
frame1 = pygame.transform.scale(frame1,(150,150))
frame2 = pygame.image.load("blue2.png")
frame2 = pygame.transform.scale(frame2,(150,150))
frame3 = pygame.image.load("blue3.png")
frame3 = pygame.transform.scale(frame3,(150,150))

frames = [frame1,frame2,frame3,]

current_frame = 0
frame_timer = 0
pos_timer = 0
clock = pygame.time.Clock()

while True:
  screen.fill((255,0,255))
  screen.blit(frames[current_frame],(x,y))
  pygame.display.update()
  if frame_timer == 60:
    current_frame = (current_frame + 1) % len(frames)
    if current_frame == 1:
     frame_timer = 40
    else:
      frame_timer = 0
  if pos_timer == 40:
    x = x + random.randint(-2,2)
    y = y + random.randint(-2,+2)
    pos_timer = 0
  pos_timer = pos_timer + 1
  frame_timer = frame_timer + 1
  event = pygame.event.get()
  for i in event:
    if i.type == pygame.QUIT:
      sys.exit()
  clock.tick(60)
